[package]
name = "timezone-tracker"
version = "0.1.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
description = "Converting/tracking timezones of others relative to your local time."
documentation = "https://github.com/Xithrius/timezone-tracker"
homepage = "https://github.com/Xithrius/timezone-tracker"
repository = "https://github.com/Xithrius/timezone-tracker"
license = "MIT OR Apache-2.0"
keywords = ["tui", "timezones"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.24.0"
tui = { version = "0.18.0", default-features = false, features = [ "crossterm" ] }
serde = { version = "1.0.137", features = [ "derive" ] }
tokio = { version = "1.19.2", features = [ "full" ] }
rusqlite = "0.27.0"
regex = "1.5.6"
unicode-width = "0.1.9"
unicode-segmentation = "1.9.0"
chrono = "0.4.19"
toml = "0.5.8"
rustyline = "9.1.2"
color-eyre = "0.6.1"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.27.0", features = [ "winsqlite3" ] }

[[bin]]
bench = false
path = "src/main.rs"
name = "tzt"
