[package]
name = "timezone-tracker"
version = "0.1.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Converting/tracking timezones of others relative to your local time."
repository = "https://github.com/Xithrius/timezone-tracker"

[dependencies]
regex = "1.5"
anyhow = "1.0"
tui = "0.16.0"
termion = "1.5"
rand = "0.8.4"
unicode-width = "0.1.5"
chrono = "0.4"
toml = "0.5.8"
serde = "1.0.130"
rusqlite = "0.25.3"
