[package]
name = "timezone-tracker"
version = "0.1.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Converting/tracking timezones of others relative to your local time."
repository = "https://github.com/Xithrius/timezone-tracker"

[dependencies]
regex = "1.5"
anyhow = "1.0"
diesel = { version = "1.4.4", features = [ "sqlite" ]}
dotenv = "0.15.0"

