[package]
name = "timezone-tracker"
version = "0.1.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Converting/tracking timezones of others relative to your local time."
repository = "https://github.com/Xithrius/timezone-tracker"

[dependencies]
crossterm = "0.22.1"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
regex = "1.5"
anyhow = "1.0.52"
rand = "0.8.4"
unicode-width = "0.1.9"
unicode-segmentation = "1.8.0"
chrono = "0.4"
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
rusqlite = { version = "0.26.1", features = ["winsqlite3"] }
tokio = { version = "1.15.0", features = ["full"] }
rustyline = "9.0.0"
maplit = "1.0.2"

[[bin]]
bench = false
path = "src/main.rs"
name = "tzt"
