[terminal]
# The delay in milliseconds between terminal updates.
tick_delay = 30

[frontend]
# The format of the date and time outputs. Formats can be found at https://strftime.org/.
time_format = "%c"

# Which side the information should be aligned to.
alignment = "right"

# The amount of padding that the main window should have.
padding = 0

# The maximum length a username can be.
maximum_username_length = 30
